# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0003_auto_20160426_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Provincia/Estado')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborative_crm.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
