# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0004_auto_20160427_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collaborative_crm.State'),
            preserve_default=False,
        ),
    ]
