# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0005_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogEntryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.AddField(
            model_name='contactchangelogentry',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborative_crm.ChangeLogEntryType'),
        ),
    ]
