# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0007_contactchangelogentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactchangelogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
