# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborative_crm', '0008_auto_20160429_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImages',
            new_name='PropertyImage',
        ),
        migrations.AddField(
            model_name='propertychangelogentry',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborative_crm.ChangeLogEntryType'),
        ),
        migrations.AddField(
            model_name='propertychangelogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
