# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0010_userextension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='id',
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
