# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0011_auto_20160502_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpropertyrelationship',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
