# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0012_contactpropertyrelationship_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(default='', max_length=20000, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='propertychangelogentry',
            name='new_value',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Nuevo valor'),
        ),
        migrations.AlterField(
            model_name='propertychangelogentry',
            name='old_value',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Viejo valor'),
        ),
    ]
