# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0015_auto_20160503_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpropertyrelationship',
            old_name='contact_property_relationship_type',
            new_name='type',
        ),
    ]
