# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborative_crm', '0016_auto_20160503_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsearchelement',
            old_name='contact_search',
            new_name='search',
        ),
        migrations.AddField(
            model_name='contactsearch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactsearchelement',
            name='operation',
            field=models.CharField(default='', max_length=50, verbose_name='Operaci\xf3n'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsearchelement',
            name='values',
            field=models.CharField(max_length=20000, verbose_name='Valores'),
        ),
    ]
