# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:00
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0018_contactsearch_commentary'),
    ]

    operations = [
		UnaccentExtension()
    ]
