# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0019_auto_20160509_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha alta'),
        ),
        migrations.AlterField(
            model_name='contactsearch',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
