# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0022_auto_20160510_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyextraattribute',
            old_name='valor',
            new_name='value',
        ),
    ]
