# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0024_propertyextraattribute_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='garages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cocheras'),
        ),
    ]
