# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0025_property_garages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyextraattribute',
            old_name='property',
            new_name='related_property',
        ),
        migrations.AddField(
            model_name='propertyextraattribute',
            name='unit_prefix',
            field=models.BooleanField(default=False, verbose_name='Unidad prefijo'),
        ),
    ]
