# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0027_company_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='orientation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orientaci\xf3n'),
        ),
    ]
