# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0028_property_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
