# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0029_auto_20160516_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='C\xf3digo'),
        ),
    ]
