# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0030_auto_20160516_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_company_pages', "Puede ver las pagina de la seccion 'Mi Empresa'"), ('view_config', 'Puede ver la configuracion de la empresa'), ('edit_config', 'Puede editar la configuracion de la empresa'), ('view_branches', 'Puede ver los datos de las sucursales de la empresa'), ('edit_branches', 'Puede editar los datos de las sucursales de la empresa'), ('view_agents', 'Puede ver los usuarios (agentes) de la empresa'), ('edit_agents', 'Puede editar los usuarios (agentes) de la empresa'), ('view_portals', 'Puede ver la configuracion de portales de la empresa'), ('edit_portals', 'Puede editar la configuracion de portales de la empresa'))},
        ),
    ]
