# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0031_auto_20160517_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='main_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborative_crm.Branch'),
        ),
    ]
