# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0032_userextension_main_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property',
            new_name='related_property',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_file_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nombre de archivo de imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Descripci\xf3n'),
        ),
    ]
