# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0033_auto_20160517_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='related_property',
            new_name='parent_property',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='cover_image',
            field=models.BooleanField(default=False, verbose_name='Imagen de portada'),
        ),
    ]
