# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0034_auto_20160517_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpropertyrelationship',
            old_name='property',
            new_name='parent_property',
        ),
    ]
