# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0037_auto_20160519_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='contact',
            name='alternative_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EMail alternativo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='alternative_telephone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono alternativo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborative_crm.City'),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborative_crm.Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='contact',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborative_crm.Neighborhood'),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborative_crm.State'),
        ),
        migrations.AddField(
            model_name='contact',
            name='works_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
