# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0038_auto_20160519_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertychangelogentry',
            old_name='property',
            new_name='parent_property',
        ),
    ]
