# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0041_auto_20160523_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsearch',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborative_crm.Contact'),
        ),
    ]
