# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0042_auto_20160526_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='login_attempts',
            field=models.IntegerField(default=5, verbose_name='Intentos de log-in'),
        ),
    ]
