# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0043_userextension_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
    ]
