# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0046_auto_20160602_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Detalles'),
        ),
    ]
