# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborative_crm', '0047_notification_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.BooleanField(default=True, verbose_name='Notificarme')),
                ('email', models.BooleanField(default=True, verbose_name='Enviarme email')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborative_crm.NotificationType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
