# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0051_notificationtype_order_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupnotificationconfig',
            old_name='can_see',
            new_name='can_view',
        ),
        migrations.RenameField(
            model_name='usernotificationconfig',
            old_name='can_see',
            new_name='can_view',
        ),
    ]
