# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0052_auto_20160603_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='is_massive',
            field=models.BooleanField(default=False, verbose_name='Masiva'),
        ),
    ]
