# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0054_auto_20160605_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageuserto',
            name='seen',
        ),
        migrations.AddField(
            model_name='messageuserto',
            name='red',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Le\xeddo'),
        ),
    ]
