# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0055_auto_20160605_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='T\xedtulo'),
        ),
    ]
