# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0058_userinchargeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='add_my_branch_users_to_my_charge',
            field=models.BooleanField(default=False, verbose_name='Agregar usuarios de mi sucursal a mi cargo'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='add_new_users_to_my_charge',
            field=models.BooleanField(default=False, verbose_name='Agregar nuevos usuarios a mi cargo'),
        ),
    ]
