# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0059_auto_20160608_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPrivacyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(default=True, max_length=100, null=True, verbose_name='Descripci\xf3n')),
            ],
        ),
    ]
