# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0060_companyprivacyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='privacy_config',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='collaborative_crm.CompanyPrivacyConfig'),
        ),
        migrations.AlterField(
            model_name='companyprivacyconfig',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
