# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0061_auto_20160608_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprivacyconfig',
            name='order_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='company',
            name='privacy_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='collaborative_crm.CompanyPrivacyConfig'),
        ),
    ]
