# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0063_auto_20160608_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_company_pages', "Puede ver las pagina de la seccion 'Mi Empresa'"), ('edit_config', 'Puede editar la configuracion de la empresa'), ('edit_branches', 'Puede editar los datos de las sucursales de la empresa'), ('edit_agents', 'Puede editar los usuarios (agentes) de la empresa'), ('edit_portals', 'Puede editar la configuracion de portales de la empresa'), ('config_notifications', 'Puede editar la configuracion de notificaciones de cada grupo para la empresa'))},
        ),
    ]
