# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0064_auto_20160608_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='super_agents_can_assign_user_to_contacts',
            field=models.BooleanField(default=False, verbose_name='Super agentes pueden asignar/desasignar agentes a cargo a contactos'),
        ),
        migrations.AddField(
            model_name='company',
            name='super_agents_can_assign_user_to_properties',
            field=models.BooleanField(default=False, verbose_name='Super agentes pueden asignar/desasignar agentes a cargo a propiedades'),
        ),
        migrations.AddField(
            model_name='company',
            name='super_agents_can_config_notifications',
            field=models.BooleanField(default=False, verbose_name='Super agentes pueden configurar notificaciones de grupos'),
        ),
        migrations.AddField(
            model_name='company',
            name='super_agents_can_edit_agents',
            field=models.BooleanField(default=False, verbose_name='Super agentes pueden crear/editar/eliminar agentes'),
        ),
        migrations.AddField(
            model_name='company',
            name='super_agents_can_edit_branches',
            field=models.BooleanField(default=False, verbose_name='Super agentes pueden editar sucursales'),
        ),
        migrations.AddField(
            model_name='company',
            name='super_agents_can_edit_config',
            field=models.BooleanField(default=False, verbose_name='Super agentes pueden editar configuraci\xf3n'),
        ),
    ]
