# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0065_auto_20160608_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('file_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de archivo')),
            ],
        ),
    ]
