# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative_crm', '0070_auto_20160619_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactworkflowaction',
            name='automatic_email',
            field=models.BooleanField(default=False, verbose_name='Notificar por email'),
        ),
        migrations.AddField(
            model_name='contactworkflowaction',
            name='automatic_notify',
            field=models.BooleanField(default=False, verbose_name='Notificar'),
        ),
        migrations.AddField(
            model_name='contactworkflowaction',
            name='automatic_unlink_agent',
            field=models.BooleanField(default=False, verbose_name='Desvincular agente'),
        ),
    ]
