#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

app_name = 'collaborative_crm'
urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^noticias$', views.news, name='news'),
    url(r'^noticias_datos$', views.news_data, name='news_data'),

    url(r'^(contactos|mis_contactos)$', views.contacts, name='contacts'),

    url(r'^(nuevo_contacto)$', views.contact, name='contact'),
    url(r'^(nuevo_contacto)/([^/]+)$', views.contact, name='contact'),
    url(r'^(nuevo_contacto)/(dueno|interesado)/([0-9]+)$', views.contact, name='contact'),
    url(r'^(contacto)/([0-9]+)$', views.contact, name='contact'),
    url(r'^contacto/([0-9]+)/modal$', views.contact_modal, name='contact_modal'),
    url(r'^contacto/([0-9]+)/propiedad/([0-9]+)/modal$', views.contact_modal, name='contact_modal'),
    url(r'^crear_contacto$', views.create_contact, name='create_contact'),
    url(r'^crear_contacto/nombre/([^/]+)$', views.create_contact, name='create_contact'),
    url(r'^contacto/([0-9]+)/actualizar_campo$', views.update_contact_field, name='update_contact_field'),
    url(r'^contacto/([0-9]+)/historia/([0-9]+)-([0-9]+)$', views.contact_history, name='contact_history'),
    url(r'^contacto/([0-9]+)/historia/([0-9]+)/detalles$', views.contact_history_details,
        name='contact_history_details'),
    url(r'^contacto/([0-9]+)/historia/([0-9]+)/modal', views.contact_history_modal, name='contact_history_modal'),
    url(r'^contacto/([0-9]+)/propiedades/([0-9]+)-([0-9]+)$', views.contact_properties, name='contact_properties'),
    url(r'^contacto/([0-9]+)/propiedad/([0-9]+)$', views.contact_property, name='contact_property'),
    url(r'^contacto/([0-9]+)/propiedad/([0-9]+)/actualizar_datos$', views.contact_property_update,
        name='contact_property_update'),
    url(r'^contacto/([0-9]+)/busquedas/([0-9]+)-([0-9]+)$', views.contact_searches, name='contact_searches'),
    url(r'^contacto/([0-9]+)/busqueda/([0-9]+)$', views.contact_search, name='contact_search'),
    url(r'^contacto/([0-9]+)/busqueda/([0-9]+)/actualizar_comentarios$', views.contact_search_update_commentary,
        name='contact_search_update_commentary'),
    url(r'^contacto/([0-9]+)/busqueda/([0-9]+)/eliminar$', views.delete_contact_search, name='delete_contact_search'),
    url(r'^contacto/([0-9]+)/asignar_agente$', views.contact_assign_agent, name='contact_assign_agent'),
    url(r'^contacto/([0-9]+)/asignar_agente/([0-9]+)$', views.contact_assign_agent, name='contact_assign_agent'),
    url(r'^contacto/([0-9]+)/estado/ejecutar_accion/([0-9]+)$', views.contact_execute_state_action,
        name='contact_execute_state_action'),
    url(r'^contacto/([0-9]+)/eliminar$', views.delete_contact, name='delete_contact'),

    url(r'^(propiedades|mis_propiedades)$', views.properties, name='properties'),

    url(r'^propiedad/([0-9]+)$', views.property, name='property'),
    url(r'^propiedad/([0-9]+)/(dueno|interesado)/([0-9]+)$', views.property, name='property'),
    url(r'^propiedad/([0-9]+)/detalles$', views.property_details, name='property_details'),
    url(r'^propiedad/([0-9]+)/modal$', views.property_modal, name='property_modal'),
    url(r'^propiedad/([0-9]+)/contacto/([0-9]+)/modal$', views.property_modal, name='property_modal'),
    url(r'^propiedad/([0-9]+)/modal_fichas$', views.property_files_modal, name='property_files_modal'),
    url(r'^propiedad/([0-9]+)/modal_fichas/contacto/([0-9]+)$', views.property_files_modal,
        name='property_files_modal'),
    url(r'^crear_propiedad$', views.create_property, name='create_property'),
    url(r'^propiedad/([0-9]+)/actualizar_campo$', views.update_property_field, name='update_property_field'),
    url(r'^propiedad/([0-9]+)/actualizar_atributo$', views.attribute, name='attribute'),
    url(r'^propiedad/([0-9]+)/eliminar_atributo$', views.delete_attribute, name='delete_attribute'),
    url(r'^propiedad/([0-9]+)/historia/([0-9]+)-([0-9]+)$', views.property_history, name='property_history'),
    url(r'^propiedad/([0-9]+)/historia/([0-9]+)/detalles$', views.property_history_details,
        name='property_history_details'),
    url(r'^propiedad/([0-9]+)/historia/([0-9]+)/modal', views.property_history_modal, name='property_history_modal'),
    url(r'^propiedad/([0-9]+)/imagenes/([0-9]+)$', views.property_image, name='property_image'),
    url(r'^propiedad/([0-9]+)/subir_imagenes$', views.property_upload_images, name='property_upload_images'),
    url(r'^propiedad/([0-9]+)/imagenes/([0-9]+)/editar_descripcion$', views.property_edit_image_description,
        name='property_edit_image_description'),
    url(r'^propiedad/([0-9]+)/imagenes/([0-9]+)/portada$', views.property_set_cover_image,
        name='property_set_cover_image'),
    url(r'^propiedad/([0-9]+)/imagenes/([0-9]+)/eliminar$', views.property_delete_image, name='property_delete_image'),
    url(r'^propiedad/([0-9]+)/asignar_agente$', views.property_assign_agent, name='property_assign_agent'),
    url(r'^propiedad/([0-9]+)/asignar_agente/([0-9]+)$', views.property_assign_agent, name='property_assign_agent'),
    url(r'^propiedad/([0-9]+)/(excel|pdf)/([^/]+)\.(xlsx|pdf)$', views.property_file_download,
        name='property_file_download'),
    url(r'^propiedad/([0-9]+)/(excel|pdf)/([^/]+)/([^/]+)\.(xlsx|pdf)$', views.property_file_download,
        name='property_file_download'),
    url(r'^propiedad/([0-9]+)/(excel|pdf)/email$', views.property_file_send_email, name='property_file_send_email'),
    url(r'^propiedad/([0-9]+)/(excel|pdf)/([^/]+)/email$', views.property_file_send_email,
        name='property_file_send_email'),
    url(r'^propiedad/([0-9]+)/eliminar$', views.delete_property, name='delete_property'),

    url(r'^contacto/([0-9]+)/propiedad/([0-9]+)/vincular/(dueno|interesado)$',
        views.contact_property_create_relationship, name='contact_property_create_relationship'),
    url(r'^contacto/([0-9]+)/propiedad/([0-9]+)/desvincular$', views.contact_property_destroy_relationship,
        name='contact_property_destroy_relationship'),

    url(r'^notificacion/([0-9]+)/ver$', views.notification_seen, name='notification_seen'),
    url(r'^notificaciones/ver_todas$', views.notification_seen, name='notification_seen'),

    url(r'^buscar/([^/]+)/([^/]+)$', views.search, name='search'),
    url(r'^buscar/([^/]+)/([^/]+)/([0-9]+)-([0-9]+)$', views.search, name='search'),
    url(r'^buscar/html/([^/]+)/([^/]+)$', views.search_html, name='search_html'),
    url(r'^buscar/html/([^/]+)/([^/]+)/([0-9]+)-([0-9]+)$', views.search_html, name='search_html'),

    url(r'^buscar_contactos$', views.search_contacts, name='search_contacts'),
    url(r'^buscar_propiedades$', views.search_properties, name='search_properties'),
    url(r'^contacto/([0-9]+)/buscar_propiedades$', views.search_properties, name='search_properties'),
    url(r'^contacto/([0-9]+)/buscar_propiedades/([0-9]+)$', views.search_properties, name='search_properties'),

    url(r'^mi_empresa/configuracion$', views.my_company_config, name='my_company_config'),
    url(r'^empresa/([0-9])+/logo', views.company_logo, name='company_logo'),
    url(r'^empresa/([0-9]+)/actualizar_datos$', views.company_update_data, name='company_update_data'),
    url(r'^empresa/([0-9]+)/actualizar_logo$', views.company_update_logo, name='company_update_logo'),
    url(r'^mi_empresa/actualizar_permisos$', views.my_company_update_permissions, name='my_company_update_permissions'),
    url(r'^mi_empresa/grupo/([0-9]+)/configuracion_notificaciones$', views.group_notifications_config,
        name='group_notifications_config'),
    url(r'^mi_empresa/grupo/([0-9]+)/actualizar_configuracion_notificaciones$', views.update_group_notifications_config,
        name='update_group_notifications_config'),
    url(r'^mi_empresa/guardar_workflow$', views.save_workflow, name='save_workflow'),
    url(r'^workflows/([0-9]+)/detalles$', views.workflow_details, name='workflow_details'),
    url(r'^workflows/([0-9]+)/eliminar$', views.delete_workflow, name='delete_workflow'),
    url(r'^mi_empresa/sucursales$', views.my_company_branches, name='my_company_branches'),
    url(r'^mi_empresa/sucursales/([0-9]+)$', views.my_company_branches, name='my_company_branches'),
    url(r'^empresa/([0-9]+)/sucursales/([0-9]+)/actualizar_datos$', views.branch_update_data,
        name='branch_update_data'),
    url(r'^empresa/([0-9]+)/sucursales/([0-9]+)/detalles$', views.branch_details, name='branch_details'),
    url(r'^empresa/([0-9]+)/sucursales/([0-9]+)/eliminar', views.delete_branch, name='delete_branch'),
    url(r'^mi_empresa/agentes$', views.my_company_agents, name='my_company_agents'),
    url(r'^empresa/([0-9]+)/usuarios/([0-9]+)/actualizar_datos$', views.user_update_data, name='user_update_data'),
    url(r'^empresa/([0-9]+)/usuarios/([0-9]+)/detalles$', views.user_details, name='user_details'),
    url(r'^empresa/([0-9]+)/usuarios/([0-9]+)/password_reset$', views.user_reset_password, name='user_reset_password'),
    url(r'^empresa/([0-9]+)/usuarios/([0-9]+)/eliminar$', views.delete_user, name='delete_user'),

    url(r'^mensajes$', views.messages, name='messages'),
    url(r'^mensajes/([0-9]+)$', views.messages, name='messages'),
    url(r'^crear_conversacion$', views.create_conversation, name='create_conversation'),
    url(r'^conversacion/([0-9]+)/mensajes$', views.conversation_messages, name='conversation_messages'),
    url(r'^conversacion/([0-9]+)/mensajes/(leer)$', views.conversation_messages, name='conversation_messages'),
    url(r'^conversacion/([0-9]+)/enviar_mensaje$', views.send_message, name='send_message'),

    url(r'^perfil$', views.user_profile, name='user_profile'),
    url(r'^cambiar_password$', views.change_password, name='change_password'),
    url(r'^perfil/actualizar_datos$', views.update_profile_data, name='update_profile_data'),
    url(r'^perfil/actualizar_configuracion_notificaciones$', views.update_notifications_config,
        name='update_notifications_config'),

    url(r'^geografia/paises$', views.geography_countries, name='geography_countries'),
    url(r'^geografia/pais/([0-9]+)/estados$', views.geography_states, name='geography_states'),
    url(r'^geografia/estado/([0-9]+)/ciudades$', views.geography_cities, name='geography_cities'),
    url(r'^geografia/ciudad/([0-9]+)/barrios$', views.geography_neighborhoods, name='geography_neighborhoods'),
    url(r'^geografia/buscar/([^/]+)/([^/]+)$', views.geography_search, name='geography_search'),
    url(r'^tonos/([a-z0-9]{3})/([0-9]+)$', views.get_tone, name='get_tone'),
]